# This rule is not used by the project s3-monitor-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to storage.a1010s.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-monitor-operator
    app.kubernetes.io/managed-by: kustomize
  name: bucketmonitor-viewer-role
rules:
- apiGroups:
  - storage.a1010s.io
  resources:
  - bucketmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.a1010s.io
  resources:
  - bucketmonitors/status
  verbs:
  - get
