---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.a1010s.io
  resources:
  - bucketmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.a1010s.io
  resources:
  - bucketmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - storage.a1010s.io
  resources:
  - bucketmonitors/status
  verbs:
  - get
  - patch
  - update
