apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: s3-monitor-operator
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: s3-monitor-operator
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - s3-monitor-operator-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
